Repository gdsfactory/gplugins, pull requests merged in 2024-12, with the labels that each got.

#506 fix ruff issues
  gplugins/sax/plot_model.py
Labels: bug

#508 allow numpy2
  gplugins/gmsh/uz_xsection_mesh.py
Labels: dependencies

#507 add luminescent
  docs/_toc.yml
  notebooks/luminescent.ipynb
Labels: enhancement

#509 use uv
  .github/workflows/pages.yml
  .github/workflows/test_code.yml
  .pre-commit-config.yaml
  Makefile
  README.md
  docs/_config.yml
  docs/api_design.rst
  gplugins/klayout/tests/test_dataprep_regions.py
  gplugins/klayout/tests/test_global_density.py
  gplugins/vlsir/tests/resources/pads_correct.cir
  gplugins/vlsir/tests/resources/pads_correct.scs
  gplugins/vlsir/tests/resources/pads_correct.sp
  gplugins/vlsir/tests/test_vlsir.py
  pyproject.toml
  uv.lock
Labels: documentation

#511 fix docs
  .github/workflows/pages.yml
  .github/workflows/test_code.yml
  .gitignore
  README.md
  docs/_config.yml
  docs/_toc.yml
  docs/api_design.rst
  gplugins/common/utils/get_component_with_net_layers.py
  gplugins/gmsh/get_mesh.py
  gplugins/klayout/dataprep/regions.py
  gplugins/meow/meow_eme.py
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
  gplugins/sax/build_model.py
  notebooks/klayout_dataprep.ipynb
  notebooks/luminescent.ipynb
  notebooks/path_length_analysis.ipynb
  notebooks/pso.ipynb
  notebooks/tidy3d_00_tidy3d.ipynb
  notebooks/workflow_3_cascaded_mzi.ipynb
  pyproject.toml
  uv.lock
Labels: bug, documentation

#515 unpin vlsir
  pyproject.toml
  uv.lock
Labels: dependencies

#516 update changelog
  CHANGELOG.md
Labels: documentation

#519 fix docstring
  gplugins/sentaurus/sde.py
  gplugins/tidy3d/tests/test_materials.py
Labels: documentation

#522 fix grating couplers in tidy3d
  gplugins/tidy3d/get_simulation_grating_coupler.py
  notebooks/tidy3d_00_tidy3d.ipynb
Labels: bug

#523 update readme
  README.md
Labels: documentation
