Repository gdsfactory/gplugins, pull requests merged in 2024-05, with the labels that each got.

#395 Fix Elmer tests in CI, fixes towards Palace
  .github/workflows/test_code.yml
  Makefile
  notebooks/elmer_01_electrostatic.ipynb
  notebooks/palace_01_electrostatic.ipynb
  notebooks/palace_02_fullwave.ipynb
  notebooks/sax_01_sax.ipynb
  pyproject.toml
Labels: bug, dependencies, simulations

#398 Fix SPICE plotting example notebook
  gplugins/klayout/netlist_graph.py
  gplugins/klayout/netlist_spice_reader.py
  gplugins/klayout/plot_nets.py
  notebooks/11_get_netlist_spice.ipynb
Labels: bug

#401 improve SDL interconnect docs
  docs/_toc.yml
  gplugins/__init__.py
  gplugins/common/utils/get_scattering.py
  gplugins/sax/models.py
  gplugins/spice/__init__.py
  gplugins/spice/spice_to_yaml.py
  gplugins/spice/tests/__init__.py
  gplugins/spice/tests/test_interconnect.py
  gplugins/tidy3d/get_simulation_grating_coupler.py
  gplugins/tidy3d/modes.py
  notebooks/11_get_netlist_spice.ipynb
  notebooks/21_schematic_driven_layout_lumerical.ipynb
Labels: documentation

#409 fix tests
  Makefile
  pyproject.toml
Labels: bug

#410 Path analysis from gds
  gplugins/klayout/netlist_spice_reader.py
  gplugins/klayout/plot_nets.py
  gplugins/path_length_analysis/path_length_analysis.py
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
  notebooks/11_get_netlist_spice.ipynb
  notebooks/path_length_analysis.ipynb
Labels: enhancement

#411 fix notebooks
  gplugins/gmeep/write_sparameters_meep.py
  notebooks/meshing_03_2D_uz_mesh.ipynb
  notebooks/path_length_analysis.ipynb
  pyproject.toml
Labels: bug
