Repository gdsfactory/gplugins, pull requests merged in 2024-02, with the labels that each got.

#329 require labels on PRs
  .github/release-drafter.yml
  .github/workflows/require-labels.yml
  .github/workflows/stale.yml
Labels: github_actions

#332 pin latest working version of jax and jaxlib for sax to work
  pyproject.toml
Labels: dependencies

#334 pin older version of meshwell
  pyproject.toml
Labels: dependencies

#338 Mention correct pinned pyvis version
  gplugins/klayout/plot_nets.py
Labels: github_actions

#339 basic python-driven density analytics, using klayout tiling processor
  gplugins/klayout/get_density.py
  gplugins/klayout/tests/test_density.py
Labels: enhancement

#340 better global density estimation
  gplugins/klayout/get_density.py
  gplugins/klayout/tests/test_global_density.py
Labels: maintenance

#342 better pyproject
  pyproject.toml
Labels: github_actions
