Repository gdsfactory/gplugins, pull requests merged in 2024-06, with the labels that each got.

#419 Strip brackets from model name in Calibre SPICE reader
  gplugins/klayout/netlist_spice_reader.py
  pyproject.toml
Labels: enhancement

#421 tidy3d fixes
  gplugins/common/base_models/component.py
  gplugins/tidy3d/component.py
Labels: bug

#428 fix write_drc
  gplugins/klayout/drc/write_drc.py
Labels: bug

#429 update vlsirtools
  gplugins/klayout/drc/samples/drc_errors.py
  gplugins/path_length_analysis/test_pathlength_extraction.py
  notebooks/klayout_drc.ipynb
  notebooks/lumerical_2_interconnect.ipynb
  pyproject.toml
Labels: dependencies
