Repository gdsfactory/gplugins, pull requests merged in 2024-07, with the labels that each got.

#436 Update path length analysis
  .gitignore
  Makefile
  gplugins/gmeep/get_meep_geometry.py
  gplugins/gmeep/get_simulation.py
  gplugins/gmeep/write_sparameters_meep.py
  gplugins/gmeep/write_sparameters_meep_batch.py
  gplugins/gmeep/write_sparameters_meep_mpi.py
  gplugins/path_length_analysis/path_length_analysis.py
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
Labels: bug

#438 Fix path length
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
  notebooks/path_length_analysis.ipynb
Labels: bug

#441 fix meow
  gplugins/gfviz/netlist.py
  gplugins/meow/meow_eme.py
  notebooks/11_get_netlist.ipynb
  pyproject.toml
Labels: bug, maintenance

#443 fixed plot_model xlabel
  gplugins/sax/plot_model.py
Labels: bug

#447 Improve path extraction from GDS
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
Labels: bug, enhancement

#442 Fix klayout netlist
  gplugins/klayout/get_netlist.py
  gplugins/klayout/plot_nets.py
  gplugins/lumerical/interconnect.py
  gplugins/spice/tests/test_interconnect.py
  gplugins/tidy3d/tests/tests_sparameters/test_simulation.py
  gplugins/vlsir/tests/test_vlsir.py
  notebooks/11_get_netlist.ipynb
Labels: bug, help wanted

#405 Run sim in `elmer_01_electrostatic.ipynb`
  notebooks/elmer_01_electrostatic.ipynb
Labels: documentation, simulations
