Repository gdsfactory/gplugins, pull requests merged in 2024-08, with the labels that each got.

#453 Robust path length extraction
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
Labels: enhancement, Verification, python

#450 fix docs
  .gitignore
  docs/_config.yml
  docs/_toc.yml
  gplugins/devsim/get_simulation.py
  gplugins/devsim/get_solver.py
  gplugins/gfviz/netlist.py
  gplugins/gmeep/get_meep_geometry.py
  gplugins/gmeep/get_simulation_grating_fiber.py
  gplugins/gmsh/xyz_mesh.py
  gplugins/meow/meow_eme.py
  gplugins/path_length_analysis/path_length_analysis.py
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
  gplugins/schematic_editor/__init__.py
  gplugins/schematic_editor/circuitviz.py
  gplugins/schematic_editor/picmodel.py
  gplugins/schematic_editor/schematic_editor.py
  gplugins/sentaurus/sde.py
  gplugins/sentaurus/sprocess.py
  notebooks/11_get_netlist.ipynb
  notebooks/20_schematic_driven_layout.ipynb
  notebooks/elmer_01_electrostatic.ipynb
  notebooks/femwell_02_heater.ipynb
  notebooks/klayout_drc.ipynb
  notebooks/meep_01_sparameters.ipynb
  notebooks/meep_03_fields.ipynb
  notebooks/meow_01.ipynb
  notebooks/meshing_02_2D_xy_mesh.ipynb
  notebooks/meshing_03_2D_uz_mesh.ipynb
  notebooks/meshing_04_refinement.ipynb
  notebooks/meshing_05_3D.ipynb
  notebooks/path_length_analysis.ipynb
  notebooks/sax_01_sax.ipynb
  notebooks/tidy3d_00_tidy3d.ipynb
  notebooks/workflow_2_ring.ipynb
Labels: bug

#454 update sax notebook
  notebooks/.gitignore
  notebooks/sax_01_sax.ipynb
Labels: bug

#455 fix notebooks
  docs/_config.yml
  docs/_toc.yml
  gplugins/common/base_models/component.py
  gplugins/gmsh/get_mesh.py
  gplugins/gmsh/tests/test_meshing_3D.py
  gplugins/gmsh/uz_xsection_mesh.py
  gplugins/gmsh/xy_xsection_mesh.py
  gplugins/gmsh/xyz_mesh.py
  gplugins/sax/parameter.py
  notebooks/11_get_netlist.ipynb
  notebooks/11_get_netlist_spice.ipynb
  notebooks/path_length_analysis.ipynb
  notebooks/sax_02_model_extraction.ipynb
  notebooks/sax_03_variability_analysis.ipynb
  notebooks/tidy3d_00_tidy3d.ipynb
  notebooks/workflow_3_cascaded_mzi.ipynb
Labels: bug

#458 Fix netlist extraction issue
  gplugins/klayout/get_netlist.py
Labels: bug

#459 Fix sax and vlsir tests
  gplugins/sax/parameter.py
  gplugins/sax/tests/test_parameters.py
  gplugins/vlsir/tests/resources/pads_correct.cir
  gplugins/vlsir/tests/resources/pads_correct.scs
  gplugins/vlsir/tests/resources/pads_correct.sp
  gplugins/vlsir/tests/test_vlsir.py
Labels: bug

#461 Improvements to path length code
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
Labels: bug

#462 rename validate call
  gplugins/modes/find_coupling_vs_gap.py
  gplugins/modes/find_neff_vs_width.py
  gplugins/sax/plot_model.py
Labels: dependencies

#464 pin vlsir
  pyproject.toml
Labels: dependencies

#465 add logo
  docs/_config.yml
  docs/_static/logo_black.png
  docs/_static/logo_white.png
Labels: documentation, enhancement

#466 update pins
  docs/_config.yml
  pyproject.toml
Labels: dependencies

#478 Fix path-length extraction of bbox-like polygons
  gplugins/path_length_analysis/path_length_analysis_from_gds.py
Labels: bug
