Repository gdsfactory/gplugins, pull requests merged in 2024-04, with the labels that each got.

#371 Improve KLayout-based SPICE handling to support Calibre LVS with generic devices
  gplugins/klayout/netlist_graph.py
  gplugins/klayout/netlist_spice_reader.py
  gplugins/klayout/plot_nets.py
  gplugins/klayout/tests/test_netlist_spice_reader.py
  gplugins/klayout/tests/test_plot_nets.py
Labels: Verification, feature

#373 Better error for wrong `top_cell` in netlist to networkx
  gplugins/klayout/netlist_graph.py
Labels: enhancement

#375 fix autolabeler
  .github/workflows/release-drafter.yml
  .github/workflows/require-labels.yml
Labels: bug

#376 update jaxlib and flax
  gplugins/path_length_analysis/path_length_analysis.py
  pyproject.toml
Labels: maintenance

#377 improve femwell plugin
  gplugins/femwell/mode_solver.py
  gplugins/gmsh/get_mesh.py
  notebooks/femwell_01_modes.ipynb
Labels: maintenance

#380 small doc fixes
  docs/_toc.yml
  gplugins/femwell/mode_solver.py
  gplugins/klayout/drc/count_drc.py
  gplugins/klayout/tests/test_global_density.py
Labels: bug

#363 add gfviz
  .gitignore
  .pre-commit-config.yaml
  gplugins/gfviz/Makefile
  gplugins/gfviz/__init__.py
  gplugins/gfviz/b64.py
  gplugins/gfviz/gfviz.py
  gplugins/gfviz/netlist.py
  gplugins/gfviz/serve.py
  gplugins/gfviz/static/b64.js
  gplugins/gfviz/static/schemedit.js
  gplugins/gfviz/static/schemedit.wasm
  gplugins/gfviz/templates/example.json
  gplugins/gfviz/templates/index.html
  notebooks/11_get_netlist.ipynb
  pyproject.toml
Labels: enhancement, feature

#382 tcad scripts
  .gitignore
  .pre-commit-config.yaml
  gplugins/gmsh/parse_gds.py
  gplugins/gmsh/uz_xsection_mesh.py
  gplugins/sentaurus/mask_sde.py
  gplugins/sentaurus/mask_sprocess.py
  gplugins/sentaurus/sde.py
  gplugins/sentaurus/sdevice.py
  gplugins/sentaurus/sprocess.py
  gplugins/sentaurus/svisual.py
Labels: enhancement

#385 Support custom IO streams in `execute_and_stream_output`
  gplugins/common/utils/async_helpers.py
Labels: enhancement, python

#386 allow mmi imbalance
  gplugins/sax/models.py
  notebooks/11_get_netlist.ipynb
  pyproject.toml
Labels: enhancement

#378 update tidy3d
  pyproject.toml
Labels: dependencies

#387 Add padding layer to gplugins
  gplugins/tidy3d/get_simulation_grating_coupler.py
  notebooks/femwell_01_modes.ipynb
Labels: enhancement
