Repository gdsfactory/gplugins, pull requests merged in 2025-05, with the labels that each got.

#583 removing gdstk dependencies anywhere other than the tidy3d module
  gplugins/common/utils/get_component_with_local_layers.py
  gplugins/gfviz/netlist.py
  gplugins/gmeep/write_sparameters_meep_mpi.py
  pyproject.toml
  uv.lock
Labels: enhancement, dependencies

#588 update changelog
  CHANGELOG.md
Labels: documentation

#589 remove meshwell dep
  gplugins/common/base_models/component.py
  gplugins/sax/build_model.py
  gplugins/sax/integrations/__init__.py
  gplugins/sax/integrations/femwell_waveguide_model.py
  gplugins/sax/integrations/meep_FDTD_model.py
  gplugins/sax/integrations/meow_eme_model.py
  pyproject.toml
Labels: dependencies

#590 Add dockerfile
  .dockerignore
  Dockerfile
Labels: maintenance
