Repository gdsfactory/gplugins, pull requests merged in 2025-06, with the labels that each got.

#596 fix_mypy
  gplugins/common/utils/get_sparameters_path.py
  gplugins/klayout/dataprep/regions.py
  gplugins/klayout/drc/count_drc.py
  gplugins/sax/interpolators.py
  gplugins/sax/mlp.py
  gplugins/sax/tests/test_mzi.py
  gplugins/sax/tests/test_mzi_lattice.py
  gplugins/tidy3d/materials.py
  gplugins/tidy3d/types.py
Labels: bug

#597 fix palace
  gplugins/palace/get_capacitance.py
  gplugins/palace/get_scattering.py
Labels: bug

#608 More Voronoi extraction tests
  gplugins/path_length_analysis/test_pathlength_extraction_from_gds.py
  pyproject.toml
Labels: enhancement

#609 bump sax
  .github/workflows/test_code.yml
  .gitignore
  Makefile
  gplugins/common/config.py
  gplugins/sax/__init__.py
  gplugins/sax/models.py
  gplugins/sax/plot_model.py
  gplugins/sax/strategy.py
  gplugins/sax/tests/test_mzi_lattice.py
  notebooks/data/coupler_G224n_L20_S220.csv
  notebooks/data/coupler_G224n_L20_S220.yml
  notebooks/sax_01_sax.ipynb
  pyproject.toml
  uv.lock
Labels: dependencies
