Repository gdsfactory/gplugins, pull requests merged in 2025-08, with the labels that each got.

#620 better title for plot model
  gplugins/sax/plot_model.py
Labels: bug

#621 sax plot_model: better log scaling, better labelling
  gplugins/sax/plot_model.py
Labels: enhancement

#626 improve changelog
  CHANGELOG.md
Labels: documentation

#627 bump sax to 0.15.14
  pyproject.toml
Labels: dependencies
